### ISSUE TITLE
ct:pal crashes on erlang:19 image

### ISSUE THREAD

**Issue by NAR** [erlang/docker-erlang-otp#135]
Hello!

Recently our common_test suites started to fail in our (gitlab-runner) CI environment with errors like this:

        {dir_SUITE,init_per_testcase,
            {{noproc,
                 {gen_event,call,
                     [cth_readable_logger,cth_readable_failonly,
                      {ct_pal,
                          [10,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,
                           45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,
                           45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,
                           45,45,10,"2018-06-06 19:41:49.002",10,116,101,115,
                           116,32,105,110,105,116,32,39,"bic",39,58,32,68,101,
                           108,101,116,101,100,32,107,101,121,115,32,"[]",10,
                           10]}]}},
             [{gen_event,call1,3,[{file,"gen_event.erl"},{line,207}]},
              {cthr,pal,4,
                  [{file,
                       "/usr/src/rebar3-src/_build/default/lib/cth_readable/src/cthr.erl"},
                   {line,74}]},

As far as I understand the gitlab CI environment and our setup, the CI job fetches the erlang:19 Docker image:

Using docker image sha256:2ea95f0c3147e50b79b4fcd28c955c80c2e57eb20fb8ff61bb8ed1873d0b6957 for erlang:19

and executes our test suite in that image. Our code did not change, but it looks like the image did change, at least at the latest successful test I see this in the logs:

Using docker image sha256:e36b5300c4cf2f504f0222ea66bbf81fb2e514ad88cb93f111b5e85e7893b99a for erlang:19

Do you know what changed?

**Comment by tsloughter** [comment]
@NAR can we close this?

The issue is having a module named `logger` in your project and rebar3 being upgraded to support OTP-21 logger, correct?

**Comment by ferd** [comment]
That is what the problem is, yeah. This is a name clash with a future OTP module.

**Comment by NAR** [comment]
Yes, I think this issue can be closed.
