### ISSUE TITLE
Broken SSL on erlang:19-slim

### ISSUE THREAD

**Issue by codeadict** [erlang/docker-erlang-otp#181]
The merge of #175 broke the crypto module on tag `19-slim`.

**Steps to reproduce:**

Run: 

```console
docker run -it --rm erlang:19-slim erl -s crypto
```

and you will get:

```erlang
{"init terminating in do_boot",{undef,[{crypto,start,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ()
```

**Comment by getong** [comment]
Thanks for reporting this, #182 might be the solution. One day or two, we will fix it and update it to the docker hub.

**Comment by codeadict** [comment]
Thanks s much for the quick response @getong

**Comment by getong** [comment]
docker-library/official-images#5094 is created.

**Comment by getong** [comment]
The pr is merged, close it.
