### ISSUE TITLE
leaving ca-certificates installed?

### ISSUE THREAD

**Issue by tsloughter** [erlang/docker-erlang-otp#190]
When creating a CircleCI Orb I wanted to use the official docker images but it turns out the use of caching in CircleCI requires the image to have ca-certificates installed. Currently the image build will remove it after having installed it for the build.

So every job requires to first install the package. It isn't a blocker of course, https://github.com/tsloughter/rebar3_orb/blob/master/src/orb.yml#L33 

But I figured I'd bring it up since I would suspect it is a fairly small package. Yea, it is 196kb.

**Comment by c0b** [comment]
the PR#101 was ready for it be pinned in, from this comment there are choices and someone want to use other cert packages

https://github.com/erlang/docker-erlang-otp/pull/101#issuecomment-354838206

**Comment by tsloughter** [comment]
Oh cool, missed that. And certifi is different. I'd suggest reopening that and merging.
