### ISSUE TITLE
Rebuild Alpine images using Alpine 3.10

### ISSUE THREAD

**Issue by rinpatch** [erlang/docker-erlang-otp#235]
Current Alpine images are built with Alpine 3.9.4. When using the image to build OTP releases with bundled ERTS, we noticed that it won't run on Alpine 3.10, exiting with `dlsym: Resource temporarily unavailable`.

According to [this bug](https://bugs.alpinelinux.org/issues/9983) it is because of musl changes and just needs a rebuild on a newer musl version. I wasn't able to find anything suspicious in the musl changelog, but swapping `erlang:alpine` with `alpine:latest` and installing Erlang from Alpine's repos fixed the issue and now OTP releases built in the container run on both 3.10 and below.

**Comment by tsloughter** [comment]
I'll note here that there were issues building on 3.10 but @beardedeagle got it working so we should talk to him and look at how his images are building on 3.10.

**Comment by wuhkuh** [comment]
I have 3.10 working as well, by making use of a patchfile. Are you accepting a PR for this issue?

**Comment by tsloughter** [comment]
@wuhkuh please send a PR.

**Comment by tsloughter** [comment]
Note I opened a PR on OTP for this https://github.com/erlang/otp/pull/2346

But think it may be best to change it to just error if hipe is enabled.

**Comment by beardedeagle** [comment]
Yes I'm currently using the patchfile as well, but will be releasing a different image in parallel with hipe disabled as well

**Comment by zbikmarc** [comment]
Any hope to have this images available soon?

**Comment by tsloughter** [comment]
@zbikmarc they will have to be with hipe disabled. Which I think is fine for just the alpine image if it is clear in the readme and add a label that says `hipe=off` or something to the image. What do others thing?

**Comment by beardedeagle** [comment]
My plan was to provide both with explicit call out to patch file, in case people need hipe for some reason I don't know about.

**Comment by tsloughter** [comment]
I think for the official images the patch shouldn't be used.

Could also just wait for 22.0.8 which will disable hipe automatically when built on alpine.

**Comment by garazdawi** [comment]
We release scheduled patches about every 3 months. OTP-22.1 will be released next week and includes the hipe patch.

**Comment by tsloughter** [comment]
@garazdawi ah, perfect, thanks!
