### ISSUE TITLE
Remove c0b from maintainers

### ISSUE THREAD

**Issue by dolfinus** [erlang/docker-erlang-otp#353]
Hello.

I've discovered that manifest of Erlang image in the Docker official-images repo is pointing to this user: https://github.com/c0b/
https://github.com/docker-library/official-images/blob/ffc1738524f0876757f273af51b40c8130b4bda4/library/erlang#L3

He was the first one who made Docker images for Erlang and Elixir, but disappeared few years ago. Is it correct to still mention this user in a script which generates this manifest file?
https://github.com/erlang/docker-erlang-otp/blob/563db88eea30a7ae5bc5aea6643b6b186a555c35/generate-stackbrew-library.sh#L61

**Comment by getong** [comment]
It makes sense, and the two repoes are still under maintainance with his code.
