### ISSUE TITLE
Use Debian 11 based images for building new Erlang 24

### ISSUE THREAD

**Issue by kpy3** [erlang/docker-erlang-otp#362]
Since Debian 11 has been released and new docker images are ready, it seems images for new Erlang releases can be upgraded to new release.

Please upgrade base images for Erlang to new Debian 11. 🙏

**Comment by getong** [comment]
It is usually updated after the new debian is released one month or two later, because  there are quite a lot images are based on the old debian release.

**Comment by sparkertime** [comment]
Have folks kicked the tires on this upgrade? I am not a Docker pro but since this went live, I'm consistently getting errors launching erlang with the new `erlang:24` image of the sort
```
lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /app/erts-12.2/bin/beam.smp)
```

Downgrading to the 23 image seems to do the trick though.
