### ISSUE TITLE
Erlang 25 for arm64 seg faults

### ISSUE THREAD

**Issue by carlhoerberg** [erlang/docker-erlang-otp#400]
```
✗ podman run -it --rm --platform linux/arm64 erlang:25 bash
root@24f5e5903b75:/# erl
Segmentation fault (core dumped)
```
same result with docker according to my colleagues. is qemu-aarch64-static and the jit interfering maybe? tried to disable jit, but:

```
✗ podman run -it --rm --platform linux/arm64 -e ERL_FLAGS="-emu_flavor emu" erlang:25
erlexec: Invalid emulator type or flavor. Available combinations are:
  -emu_flavor smp
```

**Comment by garazdawi** [comment]
There is a bug in qemu when using x^w memory mappings for the JIT:ed code. You can read about it here: https://erlangforums.com/t/otp-25-0-rc3-release-candidate-3-is-released/1317/25. So, the image will work when you run it on arm64 hardware, but not when emulated by quemu.

The images provided by this repository do not include the non-jit emulator, so you will have to build your own if you want to run Erlang in qemu.

**Comment by carlhoerberg** [comment]
ok, thank you!
