### ISSUE TITLE
Request for image for 26.1

### ISSUE THREAD

**Issue by kivra-pauoli** [erlang/docker-erlang-otp#450]
👋 

I don't know all the details behind how/when an image is created after an OTP release is done, so I'm gently reminding here of the need for a 26.1 release. I'm willing to help if help is required.

This might tie into #449, but I wanted to separate scopes for easier tracking...

Thanks.

**Comment by epinault** [comment]
there is also a 26.1.1 already released

**Comment by kivra-pauoli** [comment]
Yeah, and there's a request/idea on how to automate this, but I think we're not there yet 😄
