### ISSUE TITLE
Should we use REBAR3_VERSION="3.20.0" for OTP22/23 instead?

### ISSUE THREAD

**Issue by kianmeng** [erlang/docker-erlang-otp#473]
I have noticed that starting from Rebar3 3.21 release, the support for OTP 23 have been deprecated, see https://github.com/erlang/rebar3/releases/tag/3.21.0 and https://github.com/erlang/rebar3/pull/2791

Should to Rebar3 version in Dockerfile for OTP 23 and 22 set to 3.20.0 instead?

https://github.com/erlang/docker-erlang-otp/blob/8b812830f95216a3d8a253c24af2c55a1da4935b/23/Dockerfile#L3-L4

https://github.com/erlang/docker-erlang-otp/blob/8b812830f95216a3d8a253c24af2c55a1da4935b/22/Dockerfile#L3-L4

**Comment by getong** [comment]
pr are welcome, I do not know it .

**Comment by kianmeng** [comment]
Resolves in https://github.com/erlang/docker-erlang-otp/pull/474
